# Generated by Django 5.0.6 on 2026-05-26 17:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel (MB51)'), ('sap_procurement', 'SAP Procurement (ME2M)'), ('utility_electricity', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=30)),
                ('scope', models.CharField(choices=[('1', 'Scope 1'), ('2', 'Scope 2'), ('3', 'Scope 3')], max_length=1)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('raw_data', models.JSONField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('facility_code', models.CharField(blank=True, max_length=200)),
                ('facility_description', models.CharField(blank=True, max_length=500)),
                ('quantity_raw', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_raw', models.CharField(max_length=50)),
                ('quantity_normalized', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_normalized', models.CharField(max_length=50)),
                ('emission_factor_value', models.DecimalField(decimal_places=6, max_digits=12, null=True)),
                ('emission_factor_unit', models.CharField(blank=True, max_length=30)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=18, null=True)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicion_reasons', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('flagged', 'Flagged — Needs Attention'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit')], default='pending', max_length=20)),
                ('flag_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('original_values', models.JSONField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_records', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ingested', 'Ingested'), ('flagged', 'Flagged'), ('edited', 'Edited'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit'), ('unflagged', 'Unflagged')], max_length=20)),
                ('before_state', models.JSONField(blank=True, null=True)),
                ('after_state', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.activityrecord')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('unit', models.CharField(choices=[('per_liter', 'per Liter'), ('per_kg', 'per Kilogram'), ('per_m3', 'per Cubic Meter'), ('per_kwh', 'per kWh'), ('per_pkm', 'per Passenger-km'), ('per_room_night', 'per Room-Night'), ('per_km', 'per km')], max_length=30)),
                ('source', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['category', 'valid_to'], name='ingestion_e_categor_20b073_idx')],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='emission_factor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_records', to='ingestion.emissionfactor'),
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP — Fuel Consumption (MB51)'), ('sap_procurement', 'SAP — Procurement (ME2M)'), ('utility_electricity', 'Utility — Electricity'), ('travel', 'Corporate Travel (Concur/Navan)')], max_length=30)),
                ('filename', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, max_length=64)),
                ('row_count', models.IntegerField(default=0)),
                ('parsed_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_detail', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='core.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='activityrecord',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.ingestionrun'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'status'], name='ingestion_a_organiz_1640a9_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'scope'], name='ingestion_a_organiz_3f861c_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['organization', 'period_start', 'period_end'], name='ingestion_a_organiz_ae9699_idx'),
        ),
        migrations.AddIndex(
            model_name='activityrecord',
            index=models.Index(fields=['ingestion_run'], name='ingestion_a_ingesti_f51121_idx'),
        ),
    ]
