# Generated by Django 5.0.6 on 2026-05-26 18:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.CheckConstraint(check=models.Q(('period_end__gte', models.F('period_start'))), name='chk_activity_period_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.CheckConstraint(check=models.Q(('quantity_normalized__gte', 0)), name='chk_activity_quantity_normalized_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.CheckConstraint(check=models.Q(('scope__in', ['1', '2', '3'])), name='chk_activity_scope_valid'),
        ),
        migrations.AddConstraint(
            model_name='activityrecord',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'flagged', 'approved', 'rejected', 'locked'])), name='chk_activity_status_valid'),
        ),
    ]
